name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm build

      - name: Setup signing key
        run: |
          $keyPath = "$env:USERPROFILE\.tauri\nqlix_desktop_app.key"
          $keyDir = Split-Path $keyPath -Parent
          if (-not (Test-Path $keyDir)) {
            New-Item -ItemType Directory -Path $keyDir -Force
          }
          echo "$env:TAURI_PRIVATE_KEY" | Out-File -FilePath $keyPath -Encoding utf8
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}

      - name: Build Tauri app (Windows)
        run: pnpm tauri build
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: List Windows build artifacts
        run: |
          Write-Host "Windows build artifacts:"
          Get-ChildItem -Recurse src-tauri/target/release/bundle/ | Select-Object FullName
          
          Write-Host "`nChecking for updater files:"
          Write-Host "MSI Updater files:"
          Get-ChildItem src-tauri/target/release/bundle/msi/ -Name | Where-Object { $_ -like "*.zip*" }
          Write-Host "NSIS Updater files:"
          Get-ChildItem src-tauri/target/release/bundle/nsis/ -Name | Where-Object { $_ -like "*.zip*" }

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            src-tauri/target/release/bundle/msi/
            src-tauri/target/release/bundle/nsis/

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libssl-dev libsoup-3.0-dev

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm build

      - name: Setup signing key
        run: |
          mkdir -p ~/.tauri
          echo "$TAURI_PRIVATE_KEY" > ~/.tauri/nqlix_desktop_app.key
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}

      - name: Build Tauri app (Linux)
        run: pnpm tauri build
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: List Linux build artifacts
        run: |
          echo "Linux build artifacts:"
          find src-tauri/target/release/bundle/ -type f
          
          echo -e "\nChecking for updater files:"
          echo "AppImage files:"
          find src-tauri/target/release/bundle/ -name "*.AppImage" -o -name "*.tar.gz*"

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            src-tauri/target/release/bundle/

  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-build

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            msi/*.msi
            msi/*.zip
            msi/*.zip.sig
            nsis/*.exe
            nsis/*.zip
            nsis/*.zip.sig
            bundle/appimage/*.AppImage
            bundle/appimage/*.tar.gz
            bundle/appimage/*.tar.gz.sig
          draft: false
          prerelease: false
          body: |
            ## What's Changed
            
            This release includes the latest updates for Nqlix Desktop Application.
            
            ## Installation
            
            Download the appropriate installer for your system:
            - **Windows (MSI)**: Use the `.msi` file for automatic installation
            - **Windows (NSIS)**: Use the `.exe` file for manual installation
            - **Linux**: Use the `.AppImage` file for automatic installation
            
            ## Auto-Update
            
            The application will automatically check for updates and notify you when a new version is available.
            
            ### Updater Files Included:
            - **MSI Updater**: `.msi.zip` and `.msi.zip.sig` files
            - **NSIS Updater**: `.exe.zip` and `.exe.zip.sig` files
            - **Linux Updater**: `.tar.gz` and `.tar.gz.sig` files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}