name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        run: pnpm build

      - name: Generate updater keys (if not exists)
        run: |
          if (-not (Test-Path "$env:USERPROFILE\.tauri\nqlix_desktop_app.key")) {
            pnpm tauri signer generate -w "$env:USERPROFILE\.tauri\nqlix_desktop_app.key"
          }

      - name: Build Tauri app
        run: pnpm tauri build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/release/bundle/updater/*.json
            src-tauri/target/release/bundle/updater/*.sig
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}