name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm build

      - name: Setup signing key
        run: |
          $keyPath = "$env:USERPROFILE\.tauri\nqlix_desktop_app.key"
          $keyDir = Split-Path $keyPath -Parent
          if (-not (Test-Path $keyDir)) {
            New-Item -ItemType Directory -Path $keyDir -Force
          }
          echo "$env:TAURI_SIGNING_PRIVATE_KEY" | Out-File -FilePath $keyPath -Encoding utf8
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}

      - name: Build Tauri app
        run: pnpm tauri build
        env:
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: List build artifacts (for debugging)
        run: |
          Write-Host "Listing build artifacts:"
          Get-ChildItem -Recurse src-tauri/target/release/bundle/ | Select-Object FullName

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/release/bundle/updater/*.json
            src-tauri/target/release/bundle/updater/*.sig
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}